-- S'assurer que RLS est activé sur toutes les tables référentielles
ALTER TABLE corps ENABLE ROW LEVEL SECURITY;
ALTER TABLE grades ENABLE ROW LEVEL SECURITY;
ALTER TABLE echelles ENABLE ROW LEVEL SECURITY;
ALTER TABLE echelons ENABLE ROW LEVEL SECURITY;
ALTER TABLE postes ENABLE ROW LEVEL SECURITY;
ALTER TABLE ministeres ENABLE ROW LEVEL SECURITY;
ALTER TABLE types_documents ENABLE ROW LEVEL SECURITY;